.github/workflows/smoke-test.yml

:eyes:
(https://github.com/docker-snap/docker-snap/pull/13#issuecomment-740232256)

Upload an example "docker.snap" for testing on PRs

---

.github/workflows/smoke-test.yml
dockerd-patches/buildkit-apparmor.patch
snap/snapcraft.yaml

This is an attempt to validate #1 (although this is testing the newly updated 19.03.13 from #4, so not a *completely* fair test for that issue, but at least gives us a clue if there's light at the end of that tunnel).
**Edit:** with the backported patch from 19.03.15 (pending #13), this actually fixes #1 :partying_face:

Add basic BuildKit tests in GitHub Actions

---

.github/workflows/smoke-test.yml
snap/snapcraft.yaml

Add "libsystemd-dev" so the journald log driver can read

---

.github/workflows/smoke-test.yml
snap/snapcraft.yaml

Add "xz-utils"

---

snap/snapcraft.yaml

Update to 20.10.7

---

snap/snapcraft.yaml

See https://github.com/moby/moby/releases/tag/v20.10.9:
- CVE-2021-41092
- CVE-2021-41089
- CVE-2021-41091
- CVE-2021-41103

Update to 20.10.9

---

snap/snapcraft.yaml

Update to 20.10.11

---

snap/snapcraft.yaml

https://github.com/moby/moby/releases/tag/v20.10.14

Update to 20.10.14

---

.github/workflows/smoke-test.yml
snap/snapcraft.yaml

Add "buildx" CLI plugin

---

snap/snapcraft.yaml

Align the version with docker-ce packaging.

Bump buildx to 0.10.4

---

snap/snapcraft.yaml

Align the version with docker-ce packaging.

Bump compose-v2 to 2.15.1

---

snap/snapcraft.yaml

Addresses https://github.com/docker/roadmap/issues/257

Build with golang 1.20

---

.github/workflows/smoke-test.yml

This needs snapcore/action-build@v1.1.2 to fix network issue. See https://github.com/snapcore/action-build/issues/42

Bump GitHub Action image to ubuntu 22.04

---

patches/libnvidia-container/nvidia-0001-Fix-for-22.04-build.patch
patches/patch.sh
snap/snapcraft.yaml

This should fix FTBFS on non-arm64|amd64.

snap: arch-restrict all steps

---

snap/snapcraft.yaml

snap: correct path to tini-static

---

snap/snapcraft.yaml

- Depends on: https://github.com/canonical/docker-snap/pull/197

Upgrade to 27.4.0 

---

snap/snapcraft.yaml

This new release contains some bug fixes as shown here:
- https://github.com/moby/moby/releases/tag/v27.4.1

Upgrade to 27.4.1

---

README.md

Incentive the usage of GH discussions over the creation of new issues.
The forms already have that, but it's worth to have this tiny sentence mentioning the existence of it on the README.

doc: incentive the usage of GH discussions

---

.github/workflows/nvidia-test.yml
.github/workflows/testflinger/nvidia-job.yaml
.github/workflows/testflinger/scripts/setup.sh
.github/workflows/testflinger/scripts/test.sh

- Upgrade CUDA toolkit
- Use build matrix for distros
- Reduce setup logging verbosity
- Improve test logging
- Add snap channel to annotations

test: Improve Testflinger Nvidia testing

---

snap/snapcraft.yaml

- Closes: https://github.com/canonical/docker-snap/issues/251

Upgrade to 28.0.1

---

README.md

[skip ci]
- Closes: https://github.com/canonical/docker-snap/issues/33

doc: add bullet point about removable-media under usage

---

.github/workflows/testflinger/README.md

The workflow run menu, for reference:

Document manual Nvidia workflow run
