canonical/docker-snap

.github/workflows/smoke-test.yml
This manually applies https://github.com/snapcore/snapcraft/pull/3429 to `/usr/lib/python3/dist-packages/snapcraft/plugins/_python/_pip.py` inside our GitHub Actions build to hopefully make it work again (it's broken ATM because `plugin: python` installs pip 21 which then fails on Python 3.5 from Xenial).
=> Temporarily apply snapcraft patch for installing pip 20.x

README.md, snap/snapcraft.yaml
This PR
* adds additional info to the description. This info was already available in the README but not in the description.
* removes the line about `docker.compose` from the readme (there seems to be an alias in place)
* fixes some linter errors in the readme
Note: my previous changes to the description did not propagate to the store page. This is probably because the description in the store was manually changed. You might need to run `snapcraft upload-metadata` explicitly before the metadata in the store will be changed.
=> Add docker group instructions and certs info to description

.github/workflows/smoke-test.yml
I wanted a "main" build today, but this prevented me from getting it (and the intent was to prevent this from running on private forks and filling up their meager free storage quotas), which I think this will do a better job of.
=> Switch from detecting "pull_request" to detecting the origin repo

.github/workflows/smoke-test.yml, snap/snapcraft.yaml
Fixes #15
This will help us resolve things like https://github.com/snapcore/snapcraft/pull/3429 (which is currently blocking our ability to update the snap at all...) and hopefully let us use `stage-packages: git` instead of building our own bespoke `git` from source. :eyes:
=> Update to "base: core18"

snap/snapcraft.yaml
Now that we're on "core18", this should give us a new enough Git that we don't need our own version anymore.
=> Stop compiling Git from source

.github/workflows/smoke-test.yml, dockerd-patches/snappy-apparmor-tweaks.patch, dockerd-patches/snappy-buildkit-git-environ.patch, dockerd-patches/snappy-real-chroot.patch, snap/snapcraft.yaml
This is an alternative/upgrade to #13 to see how bad the damage is. :weary: :speak_no_evil:
=> Update to 20.10.6

registry-example.md, snap/snapcraft.yaml
This is technically a follow-up to 419af60dba5af78ff695217aaf55c8dd70c5592c, which removed the patch that enabled "/var/snap/docker/common/etc/certs.d"
=> Update "certs.d" paths

snap/snapcraft.yaml
Fixes https://github.com/docker-snap/docker-snap/issues/45
We can't expect `/etc/docker` to be empty. This issue was introduced recently in https://github.com/docker-snap/docker-snap/pull/27/
=> Replace symlink with bind for /etc/docker

.github/workflows/smoke-test.yml
(Especially to avoid failing on `snap refresh lxd`)
https://github.com/snapcore/action-build/pull/24 :eyes:
See also https://forum.snapcraft.io/t/unexpectedly-empty-response-from-the-server/23393/16?u=tianon
=> Update "snapcore/action-build" to v1.0.9

registry-example.md
In the registry example, the code suggests using the `registry:2` image. However, the recent `registry` images (from 2.7.1 onwards) have suffered a regression due to a CVE ([documented here](https://github.com/docker/distribution-library-image/issues/106)) and the suggested commands fail. 
Version 2.7.0 still works. It does suffer from the aforementioned CVE, but that may not be terribly important for a simple example like this.
=> Use registry:2.7.0 instead of broken registry:2

snap/snapcraft.yaml
The currently used docker-compose is quite old. The major update is from 2019 (only bug fixes after that in the 1.25.x series). Since then there has been changes in the compose. Our project throws below error
```
docker-compose -f tools/docker_compose/docker-compose.yaml up
ERROR: The Compose file './tools/docker_compose/docker-compose.yaml' is invalid because:
Unsupported config option for services: 'bondy.docker'
make: *** [Makefile:8: devrunall] Error 1
```
However if I build the snap with latest docker-compose the issue is fixed
=> update compose to 1.29.2

snap/snapcraft.yaml
Currently, the only way to add additional registry certificates is to manually place them in the $SNAP_DATA/etc/docker/certs.d directory. This is fine on systems where the user has an interactive shell with access to that directory, but not particularly feasible on an unattended system (i.e. Ubuntu Core). This commit adds a content interface, which allows another snap to access that directory to provision it with certificates.
=> Add docker-registry-certificates content interface slot

.github/workflows/smoke-test.yml, snap/snapcraft.yaml
The intention is to have this replace the standalone `docker-compose` / `docker.compose` command eventually too, but for now just having it available as `docker compose` is a good first step (and a good first plugin to embed).
Closes #69
=> Add "compose-v2" plugin so "docker compose" works

snap/snapcraft.yaml
We always override build steps. It means no function from go plugin is used.
Use make plugin if we use upstream makefile. Then remove make from build-packages.
Remove the workaround in buildx which is caused by go plugin.
=> Remove go plugin in snapcraft

snap/snapcraft.yaml
Launchpad base image doesn't include curl.
Failure logs:
/bin/sh: 1: curl: not found
https://launchpadlibrarian.net/656730462/buildlog_snap_ubuntu_jammy_amd64_2c5566d9cd0fad66cd6d03c0241aa293_BUILDING.txt.gz
=> Add curl to libnvidia-container parts

snap/snapcraft.yaml
It's officially EOL.
See https://github.com/docker/compose/commit/30fcb72c
=> Remove docker compose v1

README.md, snap/snapcraft.yaml
This commit adds a warning to the README and snapcraft.yaml files about usage of the `no-new-privileges` security option, which will cause container startup to fail.
=> README: add `no-new-privileges` warning

README.md, bin/nvidia-container-toolkit, snap/hooks/configure, snap/hooks/connect-plug-graphics-core22, snap/snapcraft.yaml
Add the ability to completely op-out of setup up NVIDIA support, whether the hardware is present or not, by setting snap config.
By setting `nvidia-support.disabled=true` the daemon config file will have the nvidia runtime config remove, the CDI config for nvidia will be removed too, and the `nvidia-container-toolkit` service will be skipped.
This also improves the nvidia hardware detection, by checking for the presence of a PCI device with the relevant ID.
Fixes a bug effecting first install of this snap on a system.
=> NVIDIA opt-out

.github/workflows/smoke-test.yml
This adds a simple test to check for init support, and prevent the issue: https://github.com/docker-snap/docker-snap/issues/139
=> Add simple smoke-test to ensure init is supported

bin/nvidia-container-toolkit, snap/hooks/post-refresh
This addresses two current known issues to snap refresh if nvidia support is in use.
The previous CDI config is never valid for a newer revision, as some paths contain the snap revision.
- This PR ensures the previous config is always purged
If the `nvidia-container-toolkit` service fails to start properly for some reason, it prevents the snap refresh from completing, even though dockerd would remain functional for non nvidia images use cases.
- This PR enables `nvidia-container-toolkit` to fail setting up the CDI and dockerd config, and print a warning instead.
- It also ensures that dockerd config is only attempted if CDI config is generated.
- CDI config can fail on refresh due to: `ERROR_LIB_RM_VERSION_MISMATCH` [ nvidia kernel module and user space libs do not match ].
=> Improvements to snap refresh related to nvidia support 

patches/docker-cli/local-connections-dummy-hostname.patch, patches/engine/local-connections-dummy-hostname.patch, snap/snapcraft.yaml
Without this patch, snap builds produce a snap with a non-functional docker cli and client, they fail with `http: invalid Host header`
REF: https://github.com/moby/moby/issues/45935
=> Backport patches to enable support for changes to latest golang

bin/nvidia-container-toolkit, snap/hooks/install, snap/hooks/post-refresh, snap/snapcraft.yaml
Fix bug in runtime config
Should be nvidia-container-runtime binary, not nvidia-ctk
NVIDIA GPU support works without using the full nvidia-container-runtime,
but in some cases it turns out that switching to the
nvidia-container-runtime entirely is beneficial [ ability to schedule multiple simultaneous GPU containers ]
Example usage:
```
docker run --rm --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all {image-name} {container-name}
```
=> Nvidia runtime default

snap/snapcraft.yaml
There are use cases where another snap may want to either observe or modify the contents of daemon.json. One such case is azure-iot-edge, which does some networking diagnostics based on settings it reads from that file. It only needs read access, but it is also totally feasible that unattended IoT deployments may want to configure their daemon.json in certain ways and writing via a content interface would be one of the easier ways to do that.
No strong opinions on the naming, or whether these should be collapsed into a single R/W interface (as opposed to also having the R/O version)
=> Provide content slots for ro/rw access to docker daemon config

snap/snapcraft.yaml
Compile `docker-cli` statically to avoid problems described on #132.  
Currently, the `docker-snap` is shipped with the `docker-cli` dynamically linked: 
```bash
lincoln@fenrir:~/docker/multiarch/dynamic/amd64$ ldd bin/docker
linux-vdso.so.1 (0x00007ffc5850a000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x0000719048400000)
/lib64/ld-linux-x86-64.so.2 (0x000071904a179000)
```
When shipping a companion snap based on core 20 or an older version, we encounter `GLIBC` problems due to incompatible versions: 
```bash
lincoln@fenrir:~/docker/rocker$ sudo rocker hello-world
docker: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by docker)
docker: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by docker)
```
**Note**: "Companion snap" …
=> build: compile docker-cli statically

README.md, bin/nvidia-container-toolkit, nvidia/lib, nvidia/nvidia-container-toolkit, snap/hooks/configure, snap/hooks/connect-plug-graphics-core22, snap/hooks/install, snap/hooks/post-refresh, snap/snapcraft.yaml
This enhances the nvidia runtime configuration and support, and enforces use of CDI by default.
After the versions of nvidia related parts were increased to `13.5` , the CDI generation was broken.  This led to a deeper review of the nvidia runtime configuration options, and some resulting proposed enhancements.  This also included raising a bug in the nvidia-container-toolkit, which resulted in the introduction of specified support for `library-search-paths`, which fixes the CDI generation to properly support Ubuntu Core, which will land in the `v1.15.0` release.
* https://github.com/NVIDIA/nvidia-container-toolkit/issues/82
Summary of changes:
* Bump nvidia toolkit version to `v1.15.0`
* Use CDI by default
* Ensure CDI config properly generated
* Enable choice of CDI device-name-strategy …
=> NVIDIA support - improvements relating to runtime config and CDI

README.md, nvidia/lib, nvidia/nvidia-container-toolkit, snap/snapcraft.yaml
This enables the use of nvidia runtime configuration and support on Ubuntu Classic systems also.
Summary of changes:
* Add detection of nvidia support and prereqs on Classic
* Ensure CDI config is configured correctly on Classic
* Remove nvidia related snap layouts in favour of config paths to prevent clashes with host packaging on Classic
* Update nvidia section of the README
CDI config generation requires a small opengl snap interface change, which has been merged and is in `snapd-2.63`, currently in the beta channel.
* https://github.com/snapcore/snapd/pull/13847
fixes https://github.com/docker-snap/docker-snap/issues/127
fixes https://github.com/docker-snap/docker-snap/issues/148
=> NVIDIA support - enable use on Classic systems

.github/workflows/build.yaml, .github/workflows/nvidia-test.yml, .github/workflows/smoke-test.yml
Add possibility to run nvidia workflow for artifacts of PRs and separate build and upload artifact on a dedicated workflow.
- Add: workflow to build and upload artifact
- Feat: Add possibility to run nvidia tests by passing the run-id of the wanted build workflow.
=> Change GH workflows to publish the snap to Store for Nvidia testing

.github/workflows/build.yml
Currently, the snap gets built twice on PRs that intend to merge code from a local branch.
This change sets the branch for PR triggers to `main`, avoiding runs on pushes to other local branches in a PR.
Also, enables manual triggers.
=> ci: Refine triggers to avoid replicated runs on PRs

.github/workflows/nvidia-test.yml, .github/workflows/smoke-test.yml
Remove `workflow` optional argument and set `workflow_search` to true, so the artifact can be matched based on the other given characteristics.
=> ci: Make the artifact download workflow step less dependent on build workflow name

.github/workflows/nvidia-test.yml
On NVIDIA workflow, split snap store publish and tests into different jobs.
=> ci: Split snap publish and Nvidia tests into different jobs

patches/engine/0002-snappy-apparmor-tweaks.patch, patches/engine/0003-snappy-buildkit-git-environ.patch, snap/snapcraft.yaml
- Rewrote the `snappy-apparmor-tweaks` patch to ensure it applies correctly.
- Rewrote the `snappy-buildkit-git-environ` patch to ensure it applies correctly.
- Updated Go from version **1.20** to **1.21**.
- Updated Moby from version **v24.0.5** to **v27.2.0**.
- Updated containerd from version **v1.6.21** to **v1.7.21**.
- Updated runc from version **v1.1.12** to **v1.1.13.**
- closes #167.
=> Update to version 27.2.0

.github/workflows/nvidia-test.yml
Switch to use the `docker-nvidia` job queue for running Nvidia tests. This queue is served by multiple compatible devices in the testing lab. This should improve or hopefully eliminate the wait time.
=> Use Testflinger job queue served by multiple machines

snap/snapcraft.yaml
* The bug [LP#2019931](https://bugs.launchpad.net/snapcraft/+bug/2019931) is fixed since `Snapcraft 7.3.2`, so the use of passthrough it's not necessary anymore.
* closes #142
* Revert #134
=> fix: Remove passthrough for assumes

.github/workflows/smoke-test.yml
- Related to https://github.com/canonical/docker-snap/issues/181
=> ci: add Ubuntu 20.04 and 24.04 to test runners

README.md
The `home` interface does not auto-connect when installing an unsigned snap. 
```console
$ sudo snap install --dangerous ./docker_27.4.1_amd64.snap 
docker 27.4.1 installed
$ snap connections docker 
Interface         Plug                     Slot                                 Notes
content           -                        docker:config-ro                     -
content           -                        docker:docker-executables            -
content           -                        docker:docker-registry-certificates  -
content           docker:graphics-core22   -                                    -
docker            -                        docker:docker-daemon                 -
docker            docker:docker-cli        -                                    -
docker-support …
```
=> Add manual connection command for the home interface

.github/workflows/smoke-test.yml
Add test for syslog driver.
- Depends on: https://github.com/canonical/docker-snap/pull/207
=> CI: Test for syslog

snap/snapcraft.yaml
Fix  Snapcraft build warning:
```
Warning: implicit plug assignment in 'opengl' and 'removable-media'.
Plugs should be assigned to the app to which they apply, and not implicitly
assigned via the global 'plugs:' stanza which is intended for configuration only.
```
- Fixes: https://github.com/canonical/docker-snap/issues/183
=> build: Set removable-media and opengl plugs only where is needed

upgrade.sh
This part of upgrade script:
https://github.com/canonical/docker-snap/blob/69554a091f95da4015a0f38dbb05d7dd937b151f/upgrade.sh#L113
It is designed to change the comments with URLs pointing to Dockerfile of Moby.
But it only looks for the tag version, that's why it was changing the version of other parts that matches the exact same version.
This change adds more context to the RegEx so it only matches the URLs on the comments.
[skip ci]
=> build(upgrade.sh): RegEx to match only commented URL pointing to moby Dockerfile

bin/dockerd-wrapper
[According to the kernel documentation](https://docs.kernel.org/filesystems/overlayfs.html#directories), `overlayfs` needs the additional parameters to be mounted:
```bash
mount -t overlay overlay -olowerdir=/lower,upperdir=/upper,workdir=/work /merged
```
- Fixes: https://github.com/canonical/docker-snap/issues/205
For test the changes, on an Ubuntu machine (preferable a clean install), build the snap then:
```console
ubuntu@dftd:~$ sudo snap install ./docker_27.5.1_amd64.snap --dangerous
docker 27.5.1 installed
ubuntu@dftd:~$
ubuntu@dftd:~$ sudo snap connect docker:privileged :docker-support
sudo snap connect docker:support :docker-support
sudo snap connect docker:firewall-control :firewall-control
sudo snap connect docker:network-control :network-control
sudo snap connect …
```
=> feat: Add missing parameters for mounting overlayfs

README.md, bin/dockerd-wrapper, snap/hooks/configure, snap/hooks/install, snap/snapcraft.yaml
This PR provides the changes:
- Introduces the `data-dir` [snap option](https://snapcraft.io/docs/configuration-in-snaps). 
- Defaults `data-dir` to the current value `$SNAP_COMMON/var-lib-docker`
- Add documentation on README.md with usage instructions 
- Closes: https://github.com/canonical/docker-snap/issues/64
- Fixes: https://github.com/canonical/docker-snap/issues/3
Important considerations:
-  The directory chosen to hold the engine data gets owned by the `root` user. 
- If the directory doesn't exist, but it's pointed to a location where the snap was writing access, it gets created, a side effect of https://github.com/canonical/docker-snap/pull/235/commits/3030a23ae1ba5e63393b1cd4249aca5a3964d6ce
- If the directory is pointed to some place where the docker snap isn't allowed to …
=> feat: make Docker daemon data directory configurable

README.md
Matches on the list what is seeing when listing the available architectures for Docker snap [on the store](https://snapcraft.io/docker):
=> doc: Add missing supported `riscv64` and `s390x` architectures

README.md
Add Documentation regarding the existence of Docker alias `docker-compose` poiting to the `compose` app.
[skip ci]
=> doc: docker aliases 

snap/snapcraft.yaml
- compose-v2 now in sync with Moby: 
- https://github.com/moby/moby/blob/v28.0.2/Dockerfile#L19
=> Upgrade to 28.0.2

.github/workflows/smoke-test.yml
There is no smoke-test for testing the ability to **stop containers**, and **check** if:
- https://github.com/canonical/docker-snap/blob/4418a554b08359e4b38835049f578048ae517e0a/bin/dockerd-wrapper#L4-L14
- https://github.com/canonical/docker-snap/blob/4418a554b08359e4b38835049f578048ae517e0a/patches/engine/0001-snappy-aa-profile-reload.patch#L27
Still being effective.
=> ci(smoke-test): Regression test to check non-stopping container problem

.github/workflows/smoke-test.yml
- Ubuntu 20.04 LTS runner got removed on 2025-04-15
- see: https://github.com/actions/runner-images/issues/11101
=> ci: drop Focal (ubuntu-20.04) from os test matrix

README.md, nvidia/lib
Fixes #184 
The generated CDI spec sets container base paths to ` /var/lib/snapd/hostfs/usr/bin`:
```console
$ cat /var/snap/docker/current/etc/cdi/nvidia.yaml
containerEdits:
<...>
env:
- NVIDIA_VISIBLE_DEVICES=void
<...>
mounts:
<...>
- containerPath: /var/lib/snapd/hostfs/usr/bin/nvidia-smi
hostPath: /var/lib/snapd/hostfs/usr/bin/nvidia-smi
options:
- ro
- nosuid
- nodev
- bind
```
This path is not included in the default search PATH:
```console
$ sudo docker run --rm --runtime=nvidia --gpus all ubuntu env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=1571d8996069
NVIDIA_VISIBLE_DEVICES=void
HOME=/root
```
As a result, the following binaries are not discoverable from the default search paths.
One can execute them with absolute path or after adding the …
=> Change container path for nvidia binaries to make them discoverable

.github/ISSUE_TEMPLATE/bug.yaml
Additional required info:
- `snap list snapd`: Get the **revision number** of `snapd`
- `apt list snapd`: Get the **deb package version** of `snapd`
- `apparmor_parser --version`: Check the ABI version of AppArmor.
-  `apt list apparmor`: Check the deb package version of AppArmor
- This information, together with the previous one, help to **identify** if the user is running a **custom version** of AppArmor userspace tools.
- Also, make it easier to reproduce the userspace AppArmor environment.
=> chore: require additional information on issue forms

snap/hooks/post-refresh
- Use newer bash syntax
- Check also for `NVIDIA_SUPORT_CORE` env variable on post refresh hook
=> fix: nvidia support check for Core in post-refresh

nvidia/lib
- The condition should be an if-else case (or an `|| exit 0` at the end of the statements)
=> refact: simplify graphics provider checks

snap/snapcraft.yaml
Changelog extracted from the changes:
---
- Updated the ordering of Mounts in CDI to have a deterministic output. This makes testing more consistent.
- Added NVIDIA_CTK_DEBUG envvar to hooks.
- Fixed bug in setting default for `--cuda-compat-mode` flag. This caused failures in use cases invoking the `nvidia-container-cli` directly.
- Added additional logging to the `nvidia-container-cli`.
- Fixed variable initialisation when updating the ldcache. This caused failures on Arch linux or other platforms where the `nvidia-container-cli` was built from source.
- Fix mode detection on Thor-based systems. This correctly resolves `auto` mode to `csv`.
- Fix resolution of libs in LDCache on ARM. This fixes CDI spec generation on ARM-based systems using NVML.
- Run update-ldcache hook in isolated …
=> build: upgrade nvidia parts to v1.17.8

.github/workflows/smoke-test.yml
The mirror of Debian Buster is failing due to network connections issues.
This problem can be easily reproduced by doing: `docker run --rm -it debian:buster-slim apt-get update`:
```console
$ docker run --rm -it debian:buster-slim apt-get update
Ign:1 http://deb.debian.org/debian buster InRelease
Ign:2 http://deb.debian.org/debian-security buster/updates InRelease
Ign:3 http://deb.debian.org/debian buster-updates InRelease
Err:4 http://deb.debian.org/debian buster Release
404  Not Found [IP: 151.101.178.132 80]
Err:5 http://deb.debian.org/debian-security buster/updates Release
404  Not Found [IP: 151.101.178.132 80]
Err:6 http://deb.debian.org/debian buster-updates Release
404  Not Found [IP: 151.101.178.132 80]
Reading package lists... Done
E: The repository 'http://deb.debian.org/debian …
```
=> ci(smoke-test): Use Debian tag stable-slim for simple build tests

README.md
The names on the instruction for Nvidia components for the pc-kernel snap are wrong:
```console
$ sudo snap install pc-kernel+nvidia-550-ko
error: cannot install "pc-kernel": cannot find component "nvidia-550-ko" in snap resources
$ sudo snap install pc-kernel+nvidia-550-user
error: cannot install "pc-kernel": cannot find component "nvidia-550-user" in snap resources
```
=> doc: fix name of nvidia components for pc-kernel snap

snap/snapcraft.yaml
Clear the executable stack flag on libzpool.so.x.x.x with 'execstack --clear-execstack'
When building the Docker snap for the armhf architecture, the Snap Store validation fails with the following error
> Found files with executable stack. This adds PROT_EXEC to mmap(2) during mediation which may cause security denials. Either adjust your program to not require an executable stack, strip it with 'execstack --clear-execstack ...' or remove the affected file from your snap. Affected files: lib/arm-linux-gnueabihf/libzpool.so.5.0.0 functional-snap-v2_execstack [What does this mean?](https://forum.snapcraft.io/t/snap-and-executable-stacks/1812)
=> fix: clear executable stack flag on libzpool

snap/snapcraft.yaml
The docker compose shipped on Docker Engine Community is `v2.39.1`.
- Related to: https://github.com/canonical/docker-snap/issues/312
```console
ubuntu@nn:~$ sudo docker version
Client: Docker Engine - Community
Version:           28.3.3
API version:       1.51
Go version:        go1.24.5
Git commit:        980b856
Built:             Fri Jul 25 11:34:09 2025
OS/Arch:           linux/amd64
Context:           default
Server: Docker Engine - Community
Engine:
Version:          28.3.3
API version:      1.51 (minimum version 1.24)
Go version:       go1.24.5
Git commit:       bea959c
Built:            Fri Jul 25 11:34:09 2025
OS/Arch:          linux/amd64
Experimental:     false
containerd:
Version:          1.7.27
GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
runc:
Version: …
```
=> Upgrade Docker compose to match Docker Engine Community version
